### ISSUE TITLE
Feature:  HEAD methods to read only meta information about record

### ISSUE THREAD

**Issue by atimin** [reductstore/reductstore#214]
### Current problem

Sometimes we need only check if a record with a certain timestamp exits or figure out its size. We don't need to read the whole content for it and may take all the information from HTTP headers.

### Possible solution

We need an additional endpoint `HEAD /api/v1/:bucket/:entry/`which works exactly like the `GET`method but doesnt send the record content 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rtadepalli** [comment]
Had to step out of the house to take care of some things, so I don’t have access to my Linux box. I’ll begin work on this shortly.

**Comment by rtadepalli** [comment]
Started working on this today, will have a PR up soon.

**Comment by atimin** [comment]
Hey @rtadepalli . I've added labels for records. See #121 . The `HEAD` method should return labels.  Take the latest updates from the main branch, please.

**Comment by rtadepalli** [comment]
Hi @atimin , couple of questions:
1. I am going through the [MDN pages](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD) for HEAD requests and that says that the behavior of this is going to be the exact same as a GET request, but without the body. Today, the HEAD method in the bucket API is not returning the length of the body. The `Content-Length` header is zero. Should I conform to the same behavior in this API as well?
2. What  exactly is being returned here? Everything except the record data? So this includes `x-reduct-last`, `x-reduct-time` and all the labels, correct?


Running into some C++ issues :sweat_smile: working through them slowly.

**Comment by atimin** [comment]
Hey @rtadepalli 
1. I think I missed it. Please, follow the standard. I'll create an issue to fix the bucket API
2. Yes,  and don't forget `x-reduct-error`-https://docs.reduct.store/http-api#handling-errors. I've added to the headers to send error message for all HTTP methods including HEAD

If you need any help with the API or C++, don't hesitate to ask.  You can create a discussion or ping me our discord comunity.

**Comment by atimin** [comment]
Unfortunately, I need to recover this after the Rust migration
