### ISSUE TITLE
Feature: Keep original type of record

### ISSUE THREAD

**Issue by atimin** [reductstore/reductstore#219]
### Current problem

Currently, the database ignores the `content-type` header of an HTTP request when it writes a record.  When a client reads a record it receives it as `application/octet-stream`.  In many cases, the content type is useful information, we should keep it. 

### Possible solution

We could add the `content_type` field  to the `Record`  message see (src/reduct/proto/storage/entry.proto) and use instead of `application/octet-stream` (see  `reduct::api::EntryApi::Read`)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rtadepalli** [comment]
I'd like to work on this.
