### ISSUE TITLE
Feature: Batching records 

### ISSUE THREAD

**Issue by atimin** [reductstore/reductstore#236]
### Current problem

If the database has many little records, this is not efficient to request each record separately. We could batch a few records into one HTTP response when we use the Query API.

### Possible solution

We could say the database to batch data by adding parameter into the `GET /api/v1/b/:bucket/:entry/q?batch=true` in this case it concatenates a few records into a blob and provides all  the necessary meta information in the headers:

```
--------
x-reduct-batch: true
x-reduct-<timestamp-0>: content-length=<content-lenght>, content-type=<content-type>, <label-key>=<label-type>
...
x-reduct-<temestamp-N>: ...
-------
Batched Body
```

Because many HTTP servers have a limit on the size of HTTP headers, we should limit the number of records to 128 in a batch response. Also it makes sense to add a limit on the max size of the body 16 MB.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rtadepalli** [comment]
I'm writing some code for this and an important question came to mind -- each write request can be sent with a different `Content-Type` header, even though the actual data may be of type string. Right now, using `GET` with the entry API returns the stored content type -- what do we want to do when we're batching records, if the content types of records in the batch are different?

**Comment by atimin** [comment]
For the batched response, we should send a content type for each  record separately . For the whole response Content-Type could be `application/octet-stream`.

**Comment by mounte** [comment]
I like the progress on this, you can skip my notes on the python-client repo which touches this. Should have read here first.
Keep up the great work!!
