### ISSUE TITLE
Feature: HTTP API version in headers

### ISSUE THREAD

**Issue by atimin** [reductstore/reductstore#249]
### Current problem

We increase the functionality of the database and its SDKs with each release. A user might have  unaligned an SDK and a ReductStore instance and try to use a feature of the SDK that the outdated instance doesn't support.  The database provides its version with `GET /api/v1/info` method but it is inefficient to call itbefore each SDK call. 

### Possible solution

We can send `x-reduct-api` header with the current version in an HTTP response.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by renghen** [comment]
hi I saw that something similar to this feature is already done in file 
src/http_frontend/middleware.rs
the header is call "server"
