### ISSUE TITLE
Bug: demo api token wrong

### ISSUE THREAD

**Issue by he11olx** [reductstore/reductstore#534]
### What happened?

[play.reduct.store](https://play.reduct.store/). The API token is demo-rw-45ab28842f2879ce02a8fcb3e7a2327dd6d8893ed1b68712c3469d1425a11a0.

![image](https://github.com/user-attachments/assets/1fab0062-5974-4896-b5b5-36f2796e5be4)

### Version

play.reduct.store

### OS

MacOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atimin** [comment]
Hey @he11olx, thanks for the report. The token was revoked some time ago. Please use the new one: `reductstore`.
